# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwNl7LQcFmKfxPbDTjNwg9WXDm4RAp7c
"""

import pandas as pd

file_path = '/content/WHO COVID-19 cases.csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AF")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases.csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AD")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases.csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AZ")]
print(filtr)