# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_CUF0aYk8Jw5U8A_tRFsHgq47YKkmig
"""

pip install opency-python

from google.colab.patches import cv2_imshow
import cv2
rasmn=cv2.imread(" rasm.jpg")
cv2_imshow(rasmn)

oqqora=cv2.cvtColor(rasmn,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm77=cv2.imread(" rasm2.jpg")
cv2_imshow(rasm77)

oqqora=cv2.cvtColor(rasm77,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasml=cv2.imread(" rasm4.jpg")
cv2_imshow(rasml)

oqqora=cv2.cvtColor(rasml,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)